### ISSUE TITLE
I keep getting the Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 

### ISSUE THREAD

**Issue by JumanaMSA** [WorkAroundOnline/react-nlp-annotate#8]
I've been trying to import this library to an existing react app by following the steps in the readme file but I keep getting the error in the title.
Details can be found in this link:
https://codesandbox.io/s/cranky-forest-9ro55?file=/src/index.js
What could I be doing wrong? and how should I correctly import it?
Thanks.

**Comment by seveibar** [comment]
Not sure what was wrong before (I missed the notification on this) but here's a working sandbox: https://codesandbox.io/s/react-nlp-annotate-example-0jwms?file=/src/App.js
